---

- name: Configure a server or local dev machine
  hosts: all
  gather_facts: false
  roles:
    - packages
    - ssh_keys
    - dotfiles
  vars:
    # root path for sourcing files
    working_root: /Users/gewilson/
