---

- name: Configure a server or local dev machine
  hosts: gr-oss
  gather_facts: false
  roles:
    - ssh_keys
    - dotfiles
    - packages
  vars:
    # root path for sourcing files
    working_root: /home/gwilson/
