---
- name: Set authorized_keys from github
  authorized_key:
    user: "{{ remote_user }}"
    state: present
    key: https://github.com/suprjinx.keys

- name: Copy ssh items from this host
  copy:
    src: "{{ item }}"
    dest: "/home/{{ remote_user }}/.ssh/"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0600
  with_fileglob: "/home/gwilson/.ssh/*"
