---
- name: Set authorized_keys from github
  authorized_key:
    user: "{{ remote_user }}"
    state: present
    key: https://github.com/suprjinx.keys

- copy:
    src: "{{ working_root }}/.ssh/github_id_rsa.pub"
    dest: /home/{{ remote_user }}/.ssh/github_id_rsa.pub
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0644

- copy:
    src: "{{ working_root }}/.ssh/github_id_rsa"
    dest: /home/{{ remote_user }}/.ssh/github_id_rsa
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0600

- copy:
    src: "{{ working_root }}/.ssh/config"
    dest: /home/{{ remote_user }}/.ssh/config
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0644
