---

- name: Update apt
  apt: update_cache=yes

- name: Install packages
  apt:
    pkg:
      - emacs-nox
      - tmux
      - fish
      - curl
      - dnsutils
      - jq
      - silversearcher-ag
      - docker.io

- name: Fetch bins
  shell: |
    wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 &&
    chmod a+x /usr/local/bin/yq
  become: true
