---

- name: Add latest Emacs repo
  apt_repository: repo='ppa:kelleyk/emacs'

- name: Update apt
  apt: update_cache=yes

- name: Install packages
  apt:
    pkg:
      - emacs26-nox
      - tmux
      - fish
      - curl
      - dnsutils
      - docker
      - jq
      - silversearcher-ag
      - openssh-server
