---
- git:
    repo: https://git@github.com/suprjinx/dotfiles.git
    dest: /home/{{ remote_user }}/dotfiles
    accept_hostkey: yes

- name: Run dotsync to setup symlinks
  shell: /home/{{ remote_user }}/dotfiles/dotsync.sh
